# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      myvalue: ${{ steps.set-output.outputs.myvalue }}
    steps:
      - name: Set an output value
        id: set-output
        run: echo "myvalue=hello" >> $GITHUB_OUTPUT

  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script with secret
        run: echo ${{ secrets.MY_SECRET_PASSWORD }}

  matrix-job:
    needs: generate-output
    runs-on: ubuntu-latest
    strategy:
      matrix:
        number: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: Use output from previous job
        run: echo "${{ needs.generate-output.outputs.myvalue }}-${{ matrix.number }}"
